### ISSUE TITLE
before_action not defined in Rails 3

### ISSUE THREAD

**Issue by acesuares** [flyerhzm/switch_user#101]
I am using it with Rails 3, the error is: 

````
undefined method `before_action' for SwitchUserController:Class
````

I changed

````
class SwitchUserController < ApplicationController
  before_action :developer_modes_only
````

into

````
class SwitchUserController < ApplicationController
  before_filter :developer_modes_only
````

and now it works again.

Is there a specific version for use with Rails 3 !?

**Comment by flyerhzm** [comment]
@acesuares I didn't test, but is this working?

```
  if Rails.version.to_i > 3
    before_action :developer_modes_only
  else
    before_filter :developer_modes_only
  end
```

**Comment by acesuares** [comment]
Hi, I think it would work. I am using this gem now: https://github.com/pschambacher/rails3-before_action/blob/master/lib/rails3/before_action.rb and that just aliases the actions to filters.

Yours is not the only gem that switched to Rails 4. So maybe you could mention it in the docs. I can make a pull request if you want.

**Comment by flyerhzm** [comment]
@acesuares appreciated if you can make a PR

**Comment by acesuares** [comment]
Can be closed.
