### ISSUE TITLE
no instructions for API applications

### ISSUE THREAD

**Issue by mithom** [flyerhzm/switch_user#106]
when reading the readme, it looks to me like this could be used for an API apllication as well, altough i cannot find instructions on how to do so.
Now my question before i lose a lot of my time in testing out:
* Is this possible?
* if yes, how?
* Can you add this to the readme and help even more application developers?

**Comment by flyerhzm** [comment]
@mithom it's pretty easy with api, you just need to check `lib/switch_user/provider/*` to see how to switch user internally.

**Comment by mithom** [comment]
tnx, i will give it a glance, and if good I'll see if i can add a wiki page about it (implemented something quickly myself already, but i like using gems that are designed for the purpose)
