### ISSUE TITLE
installed the gem attempted to use the hamle switch_user_select

### ISSUE THREAD

**Issue by bill-siftlocal** [flyerhzm/switch_user#107]
Got:
undefined local variable or method `switch_user_select'

**Comment by flyerhzm** [comment]
@bill-siftlocal what's your rails version?

**Comment by bill-siftlocal** [comment]
4.2.5

**Comment by flyerhzm** [comment]
@bill-siftlocal I can't reproduce it, could you set up a demo to reproduce the bug?

**Comment by rathboma** [comment]
I hit exactly the same thing. Rails 4.2.5.1

**Comment by rathboma** [comment]
Ok I found the issue. If you define your own 'SwitchUserHelper' it will override the original module and you won't get access to the select box.
