### ISSUE TITLE
Rails 6 deprecation warning 'Initialization autoloaded the constant SwitchUserHelper'

### ISSUE THREAD

**Issue by nickmc** [flyerhzm/switch_user#124]
Hi

I'm not using switch_user in my tests but Rails 6.0.2.2 gives this warning when running rspec:

> DEPRECATION WARNING: Initialization autoloaded the constant SwitchUserHelper.
> 
> Being able to do this is deprecated. Autoloading during initialization is going
> to be an error condition in future versions of Rails.
> 
> Reloading does not reboot the application, and therefore code executed during
> initialization does not run again. So, if you reload SwitchUserHelper, for example,
> the expected changes won't be reflected in that stale Module object.
> 
> This autoloaded constant has been unloaded.
> 
> Please, check the "Autoloading and Reloading Constants" guide for solutions.
>  (called from <main> at /Users/nick/code/droneportal/config/environment.rb:5)

This is due to the new Zeitwerk mode for autoloading constants. However, there is no error when running in development or production environments.

Any ideas what is going on? thanks

**Comment by mjcloutier** [comment]
Also seeing this warning in test environment after upgrading to 6.0.3.1 but not dev/prod, etc...

**Comment by TheSmartnik** [comment]
Found the issue. The problem is this gem relies on rails autloading to load constant `SwitchUserHelper` during boot. A workaround would be to not require gem in a Gemfile

```ruby
gem 'switch_user', require: false
```

But require it later in initializer

```ruby
require 'switch_user'
```

**Comment by etcook** [comment]
I ended up doing what @TheSmartnik suggested, which quieted the warning, however this made the switch_user call unavailable in the template. How can I ensure it's loaded for the views as well?

**Comment by TheSmartnik** [comment]
@etcook Hi! I've created pr to solve this, can you checkout to it to see if it helps your issue?

**Comment by flyerhzm** [comment]
@TheSmartnik awesome, I've merged the PR and pushed version 1.5.3, thanks.
