### ISSUE TITLE
Select box not showing up in production

### ISSUE THREAD

**Issue by airjoshb** [flyerhzm/switch_user#57]
Everything works in dev, but when I deploy to Heroku, the select box doesn't show when logged in as admin. I am using rails 3.2.13, devise 3.0.3, cancan 1.6.10 and rolify 3.2.0. The switch_user gem is loaded and shows up in heroku and the admin account is identical to my admin account in development. 

Any ideas?

**Comment by westonganger** [comment]
It should have stated the default setting for this in the readme
