### ISSUE TITLE
Updating from 0.9.4 to 0.9.5 now causes app hangs

### ISSUE THREAD

**Issue by supairish** [flyerhzm/switch_user#59]
Not sure what has changed since the previous version (can we get a ChangeLog?)

But now whenever our support staff tries to switch to a user, our app hangs.  From a quick look it looks like all Users are trying to be loaded in memory.  When you have 100s of thousands of Users that's not possible.  Were there recent changes in this regard?  Downgrading to 0.9.4 does fix the issue for us.

Thanks!

**Comment by kaspergrubbe** [comment]
Happens for us as well.

**Comment by flyerhzm** [comment]
the performance issue is fixed, please upgrade to version 1.0.0
