### ISSUE TITLE
switch takes ages

### ISSUE THREAD

**Issue by gshilin** [flyerhzm/switch_user#72]
I've got around 400,000 users and switch takes ages.
It also tries to load all of these users into memory.
Any ideas?

**Comment by sergey-alekseev** [comment]
@gshilin have you encountered memory issues like `Cannot allocate memory - identify`?

**Comment by flyerhzm** [comment]
@gshilin @sergey-alekseev on README, I mentioned "If there are too many users (on production), the switch_user_select is not a good choice, you should call the switch user request by yourself.", you can build an input text field, fuzzy search users by ajax, then call the switch user request.

**Comment by gshilin** [comment]
I don't use switch_user_select. The problem is in switch_user_controller#handle_request where the following line
```ruby
record = SwitchUser.data_sources.find_scope_id(params[:scope_identifier])
```
loads **ALL** users.
I'm on Rails 4.2 and ruby 2.2.2

**Comment by Whitespace** [comment]
+1, this generates a `SELECT "users".* FROM "users" WHERE "users"."deleted_at" IS NULL` for us

**Comment by flyerhzm** [comment]
it should already be fixed in master branch, could you try it?

**Comment by gshilin** [comment]
Yes, it works now, thank you
