### ISSUE TITLE
Extremely high object allocation count

### ISSUE THREAD

**Issue by sergey-alekseev** [flyerhzm/switch_user#79]
I spotted in my skylight.io dashboard that the number of objects allocated during `SwitchUserController#set_current_user` is extremely high. 20 times more than I'd consider affordable. 2.5M allocations per request.
![2015-07-11-135828_591x122_scrot](https://cloud.githubusercontent.com/assets/2371639/8633593/a2e51b20-27d8-11e5-95a2-a0399ee892ab.png)

**Comment by flyerhzm** [comment]
@sergey-alekseev what version do you use? I think I have fixed it in version 1.0.0

**Comment by sergey-alekseev** [comment]
@flyerhzm thanks for the quick response. I use `0.9.5`. I'll check `1.0.0` and let you know.

**Comment by sergey-alekseev** [comment]
Wow, much much much better now. 14.5K instead of 2.5M :+1: 
Thanks @flyerhzm.
![2015-07-11-151424_573x123_scrot](https://cloud.githubusercontent.com/assets/2371639/8633708/9bc0c7d4-27df-11e5-8643-307d2e898263.png)
