### ISSUE TITLE
Switch user as link in production

### ISSUE THREAD

**Issue by Sayanc93** [flyerhzm/switch_user#80]
The switch user as a select box using erb was working perfectly but we recently has too many users in our database so I edited the  
<%= switch_user_select %>
with
<%= link_to user.login, "/switch_user?scope_identifier=user_#{user.id}" %>
and it started giving me 
undefined local variable or method `user' for #<#<Class:0x007fbc83c89258>:0x007fbc83c880d8>
error
any idea on how to fix this or is it a gem thing?

**Comment by flyerhzm** [comment]
user is the variable you should set, nothing the gem can do

**Comment by bill-siftlocal** [comment]
That response was zero help
