### ISSUE TITLE
loader returen array and throws error: undefined method `where' for #<Array:0x000000086f88c8>

### ISSUE THREAD

**Issue by acesuares** [flyerhzm/switch_user#83]
Switch User worked fine, but at some point it stopped working.

The error it throws is:
 NoMethodError in SwitchUserController#set_current_user
undefined method `where' for #<Array:0x000000086f88c8>

I tracked the error down to data_source.rb

user = loader.call.where(identifier => scope_id.sub(scope_regexp, '')).first

Apparently, 'loader' returns an array instead of an AR collection. #where is not available for the array.

Any ideas on how to fix this?

If I replace the above line with

user = User.where(identifier => scope_id.sub(scope_regexp, '')).first

it works fine.

**Comment by flyerhzm** [comment]
@acesuares actually loader is configurable, by default

```
config.available_users = { :user => lambda { User.all } }
```

`loader` is `lambda { User.all }`, I guess you are using old rails where `User.all` returns an array, but you can change the config, see README

**Comment by acesuares** [comment]
Yes Rails 3.2.21

**Comment by flyerhzm** [comment]
@acesuares then change `User.all` to `User.load`, that's it.

**Comment by acesuares** [comment]
User.load gave the following error:

```` 
ActionView::Template::Error (wrong number of arguments (0 for 1..2)):
    13:       <ul class="right">
    14:         <% if current_user.role?(:superadmin) && Rails.env.development? %>
    15:           <li class="has-dropdown">
    16:             <%= switch_user_select %>
    17:           </li>
    18:         <% end %>
    19:         <% if current_user.role?(:admin) || current_user.role?(:superadmin) || current_user.role?(:statistiek) %>
  config/initializers/switch_user.rb:8:in `block (2 levels) in <top (required)>'
  app/views/inline_forms/_header.html.erb:16:in `_app_views_inline_forms__header_html_erb___2810128481613404564_53618560'
  app/controllers/clients_controller.rb:41:in `index'
````
It started working with something like User.where('id > 0')

**Comment by flyerhzm** [comment]
@acesuares sorry, try change to `{ :user => lambda { User } }` instead

**Comment by acesuares** [comment]
Thanks, but that was of course the first thing I tried, now it says:

````
Completed 500 Internal Server Error in 118.5ms

ActionView::Template::Error (undefined method `map' for #<Class:0x00000007365040>):
    13:       <ul class="right">
    14:         <% if current_user.role?(:superadmin) && Rails.env.development? %>
    15:           <li class="has-dropdown">
    16:             <%= switch_user_select %>
    17:           </li>
    18:         <% end %>
    19:         <% if current_user.role?(:admin) || current_user.role?(:superadmin) || current_user.role?(:statistiek) %>
  app/views/inline_forms/_header.html.erb:16:in `_app_views_inline_forms__header_html_erb___97426261078959190_79135600'
  app/controllers/clients_controller.rb:41:in `index'
````

**Comment by flyerhzm** [comment]
@acesuares sorry, long time not use rails 3, it should be `User.scoped`

**Comment by acesuares** [comment]
@flyerhzm that works! 

So why not build that in, apparently something changed and broke existing apps.
````
if Rails.version.to_i >= 4
  config.available_users = { :user => lambda { User.all } }
else
  config.available_users = { :user => lambda { User.scoped } }
end
````

Is that possible?

**Comment by flyerhzm** [comment]
@acesuares I updated README for this

**Comment by acesuares** [comment]
great!

**Comment by acesuares** [comment]
The only problem would be that in rails < 4, people will have to install the initializer AND modify it...

**Comment by flyerhzm** [comment]
@acesuares I don't have time to fix and test for rails < 4 now, I'd appreciate it if you could send me a pull request.

**Comment by acesuares** [comment]
Now, when I use:

````
config.available_users = { :user => lambda { User } }
````
the error is:
````
undefined method `map' for #<Class:0x000000062390a0>
````
but if I use
````
config.available_users = { :user => lambda { User } }
````
the error is:
````
comparison of Array with Array failed
````
and if I don't use config/initializers/switch_user.rb at all, the error is
````
comparison of Array with Array failed
````

But a couple of days ago, User.scoped worked fine.

I am sure I am doing something wrong.
````

**Comment by acesuares** [comment]
It seems, the comparison of Array with Array, comes from actionpack-3.2.21, line 477

````
grouped_options = grouped_options.sort if grouped_options.is_a?(Hash)
````

grouped_options looks like this:

````
{:Guest=>[["Guest", nil]], "User"=>[["bace@suares.com", "user_1"],["mace@suares.com", "user_2"]]}
````

If I disable the guest option,
````
config.helper_with_guest = false

````

then the problem goes away...!
