### ISSUE TITLE
Need to add route for remember_me when wildcarding routes

### ISSUE THREAD

**Issue by grhansen** [flyerhzm/switch_user#92]
My app has a wildcard route at the end of my routes file.  You need to update your readme to include the instruction to add a route for the remember_me request so that original_user gets set properly if someone wants to use the switchback functionality.

get 'switch_user/remember_user', to: 'switch_user#remember_user'

**Comment by westonganger** [comment]
@flyerhzm I think you can close this issue as I see you have recently added this to the readme
