### ISSUE TITLE
Problem in controller_guard block

### ISSUE THREAD

**Issue by shuargan** [flyerhzm/switch_user#97]
config.controller_guard = lambda { |current_user, request| current_user.admin? || Rails.env.development? }

Gettin a nil exception on current_user

undefined method `admin?' for nil:NilClass

Just updated the version and started to fail.

**Comment by flyerhzm** [comment]
@shuargan you need to define `current_user` in your controller.

**Comment by shuargan** [comment]
im using device, in my controllers is always define and never nil

**Comment by flyerhzm** [comment]
but it does complain current_user is nil.
